# Generated by Django 4.0.4 on 2022-05-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_name',
        ),
    ]
